// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/applications/me": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns the authenticated user's hackathon application. If no application exists, creates a new draft application.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Get or create application",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.Application"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Partially updates the authenticated user's application. Only fields included in the request body are updated. Application must be in draft status.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Update application",
                "parameters": [
                    {
                        "description": "Fields to update",
                        "name": "application",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.UpdateApplicationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.Application"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "409": {
                        "description": "Application not in draft status",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/check-email": {
            "get": {
                "description": "Checks if an email is registered and returns the auth method used",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Check email auth method",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email address to check",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.CheckEmailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "description": "Returns the authenticated user's profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Returns the health status of the API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "status and environment",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.CheckEmailResponse": {
            "type": "object",
            "properties": {
                "auth_method": {
                    "$ref": "#/definitions/store.AuthMethod"
                },
                "exists": {
                    "type": "boolean"
                }
            }
        },
        "main.UpdateApplicationRequest": {
            "type": "object",
            "properties": {
                "accommodations": {
                    "type": "string"
                },
                "ack_application": {
                    "type": "boolean"
                },
                "ack_mlh_coc": {
                    "type": "boolean"
                },
                "ack_mlh_privacy": {
                    "type": "boolean"
                },
                "age": {
                    "type": "integer"
                },
                "country_of_residence": {
                    "type": "string"
                },
                "dietary_restrictions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.DietaryRestriction"
                    }
                },
                "ethnicity": {
                    "type": "string"
                },
                "first_hackathon_goals": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "hackathons_attended_count": {
                    "type": "integer"
                },
                "hackathons_learned": {
                    "type": "string"
                },
                "heard_about": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "level_of_study": {
                    "type": "string"
                },
                "looking_forward": {
                    "type": "string"
                },
                "major": {
                    "type": "string"
                },
                "opt_in_mlh_emails": {
                    "type": "boolean"
                },
                "phone_e164": {
                    "type": "string"
                },
                "race": {
                    "type": "string"
                },
                "shirt_size": {
                    "type": "string"
                },
                "software_experience_level": {
                    "type": "string"
                },
                "university": {
                    "type": "string"
                },
                "why_attend": {
                    "type": "string"
                }
            }
        },
        "main.UserResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/store.UserRole"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "store.Application": {
            "type": "object",
            "properties": {
                "accommodations": {
                    "type": "string"
                },
                "ack_application": {
                    "type": "boolean"
                },
                "ack_mlh_coc": {
                    "type": "boolean"
                },
                "ack_mlh_privacy": {
                    "type": "boolean"
                },
                "age": {
                    "type": "integer"
                },
                "country_of_residence": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "dietary_restrictions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.DietaryRestriction"
                    }
                },
                "ethnicity": {
                    "type": "string"
                },
                "first_hackathon_goals": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "hackathons_attended_count": {
                    "type": "integer"
                },
                "hackathons_learned": {
                    "type": "string"
                },
                "heard_about": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "level_of_study": {
                    "type": "string"
                },
                "looking_forward": {
                    "type": "string"
                },
                "major": {
                    "type": "string"
                },
                "opt_in_mlh_emails": {
                    "type": "boolean"
                },
                "phone_e164": {
                    "type": "string"
                },
                "race": {
                    "type": "string"
                },
                "shirt_size": {
                    "type": "string"
                },
                "software_experience_level": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/store.ApplicationStatus"
                },
                "submitted_at": {
                    "type": "string"
                },
                "university": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "why_attend": {
                    "type": "string"
                }
            }
        },
        "store.ApplicationStatus": {
            "type": "string",
            "enum": [
                "draft",
                "submitted",
                "accepted",
                "rejected",
                "waitlisted"
            ],
            "x-enum-varnames": [
                "StatusDraft",
                "StatusSubmitted",
                "StatusAccepted",
                "StatusRejected",
                "StatusWaitlisted"
            ]
        },
        "store.AuthMethod": {
            "type": "string",
            "enum": [
                "passwordless",
                "google"
            ],
            "x-enum-varnames": [
                "AuthMethodPasswordless",
                "AuthMethodGoogle"
            ]
        },
        "store.DietaryRestriction": {
            "type": "string",
            "enum": [
                "vegan",
                "vegetarian",
                "halal",
                "nuts",
                "fish",
                "wheat",
                "dairy",
                "eggs",
                "no_beef",
                "no_pork"
            ],
            "x-enum-varnames": [
                "DietaryVegan",
                "DietaryVegetarian",
                "DietaryHalal",
                "DietaryNuts",
                "DietaryFish",
                "DietaryWheat",
                "DietaryDairy",
                "DietaryEggs",
                "DietaryNoBeef",
                "DietaryNoPork"
            ]
        },
        "store.UserRole": {
            "type": "string",
            "enum": [
                "hacker",
                "admin",
                "super_admin"
            ],
            "x-enum-varnames": [
                "RoleHacker",
                "RoleAdmin",
                "RoleSuperAdmin"
            ]
        }
    },
    "securityDefinitions": {
        "CookieAuth": {
            "type": "apiKey",
            "name": "sAccessToken",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "HackPortal API",
	Description:      "API for HackPortal",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
