// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/applications": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Lists all applications with cursor-based pagination and optional status filter",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "List applications (Admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pagination cursor",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by status (draft, submitted, accepted, rejected, waitlisted)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default 50, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pagination direction: forward (default) or backward",
                        "name": "direction",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.ApplicationListResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/admin/applications/stats": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns aggregated statistics for all applications",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get application stats (Admin)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.ApplicationStats"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/admin/applications/{applicationID}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns a single application by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get application by ID (Admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application ID",
                        "name": "applicationID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.Application"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/applications/me": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns the authenticated user's hackathon application. If no application exists, creates a new draft application.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Get or create application",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.Application"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Partially updates the authenticated user's application. Only fields included in the request body are updated. Application must be in draft status.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Update application",
                "parameters": [
                    {
                        "description": "Fields to update",
                        "name": "application",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.UpdateApplicationPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.Application"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "409": {
                        "description": "Application not in draft status",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/applications/me/submit": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Submits the authenticated user's application for review. All required fields must be filled and acknowledgments must be accepted. Application must be in draft status.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Submit application",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.Application"
                        }
                    },
                    "400": {
                        "description": "Missing required fields",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "409": {
                        "description": "Application not in draft status",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/check-email": {
            "get": {
                "description": "Checks if an email is registered and returns the auth method used",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Check email auth method",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email address to check",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.CheckEmailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "description": "Returns the authenticated user's profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Returns the health status of the API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "status and environment",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/superadmin/settings": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns all hackathon settings including short answer questions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "superadmin"
                ],
                "summary": "Get settings (Super Admin)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SettingsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Replaces all short answer questions with the provided array",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "superadmin"
                ],
                "summary": "Update settings (Super Admin)",
                "parameters": [
                    {
                        "description": "Questions to set",
                        "name": "settings",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.UpdateSettingsPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SettingsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.CheckEmailResponse": {
            "type": "object",
            "properties": {
                "auth_method": {
                    "$ref": "#/definitions/store.AuthMethod"
                },
                "exists": {
                    "type": "boolean"
                }
            }
        },
        "main.SettingsResponse": {
            "type": "object",
            "properties": {
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.ShortAnswerQuestion"
                    }
                }
            }
        },
        "main.UpdateApplicationPayload": {
            "type": "object",
            "properties": {
                "accommodations": {
                    "type": "string"
                },
                "ack_application": {
                    "type": "boolean"
                },
                "ack_mlh_coc": {
                    "type": "boolean"
                },
                "ack_mlh_privacy": {
                    "type": "boolean"
                },
                "age": {
                    "type": "integer",
                    "maximum": 150,
                    "minimum": 1
                },
                "country_of_residence": {
                    "type": "string",
                    "minLength": 1
                },
                "dietary_restrictions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ethnicity": {
                    "type": "string",
                    "minLength": 1
                },
                "first_name": {
                    "type": "string",
                    "minLength": 1
                },
                "gender": {
                    "type": "string",
                    "minLength": 1
                },
                "github": {
                    "description": "Social/Professional Links (all optional)",
                    "type": "string"
                },
                "hackathons_attended_count": {
                    "type": "integer",
                    "minimum": 0
                },
                "heard_about": {
                    "type": "string",
                    "minLength": 1
                },
                "last_name": {
                    "type": "string",
                    "minLength": 1
                },
                "level_of_study": {
                    "type": "string",
                    "minLength": 1
                },
                "linkedin": {
                    "type": "string"
                },
                "major": {
                    "type": "string",
                    "minLength": 1
                },
                "opt_in_mlh_emails": {
                    "type": "boolean"
                },
                "phone_e164": {
                    "type": "string"
                },
                "race": {
                    "type": "string",
                    "minLength": 1
                },
                "shirt_size": {
                    "type": "string",
                    "minLength": 1
                },
                "short_answer_responses": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "software_experience_level": {
                    "type": "string",
                    "minLength": 1
                },
                "university": {
                    "type": "string",
                    "minLength": 1
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "main.UpdateSettingsPayload": {
            "type": "object",
            "required": [
                "questions"
            ],
            "properties": {
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.ShortAnswerQuestion"
                    }
                }
            }
        },
        "main.UserResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "profilePictureUrl": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/store.UserRole"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "store.Application": {
            "type": "object",
            "properties": {
                "accommodations": {
                    "type": "string"
                },
                "ack_application": {
                    "type": "boolean"
                },
                "ack_mlh_coc": {
                    "type": "boolean"
                },
                "ack_mlh_privacy": {
                    "type": "boolean"
                },
                "age": {
                    "type": "integer",
                    "maximum": 150,
                    "minimum": 1
                },
                "country_of_residence": {
                    "type": "string",
                    "minLength": 1
                },
                "created_at": {
                    "type": "string"
                },
                "dietary_restrictions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ethnicity": {
                    "type": "string",
                    "minLength": 1
                },
                "first_name": {
                    "type": "string",
                    "minLength": 1
                },
                "gender": {
                    "type": "string",
                    "minLength": 1
                },
                "github": {
                    "type": "string"
                },
                "hackathons_attended_count": {
                    "type": "integer",
                    "minimum": 0
                },
                "heard_about": {
                    "type": "string",
                    "minLength": 1
                },
                "id": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string",
                    "minLength": 1
                },
                "level_of_study": {
                    "type": "string",
                    "minLength": 1
                },
                "linkedin": {
                    "type": "string"
                },
                "major": {
                    "type": "string",
                    "minLength": 1
                },
                "opt_in_mlh_emails": {
                    "type": "boolean"
                },
                "phone_e164": {
                    "type": "string"
                },
                "race": {
                    "type": "string",
                    "minLength": 1
                },
                "shirt_size": {
                    "type": "string",
                    "minLength": 1
                },
                "short_answer_responses": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "software_experience_level": {
                    "type": "string",
                    "minLength": 1
                },
                "status": {
                    "$ref": "#/definitions/store.ApplicationStatus"
                },
                "submitted_at": {
                    "type": "string"
                },
                "university": {
                    "type": "string",
                    "minLength": 1
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "store.ApplicationListItem": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "country_of_residence": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "hackathons_attended_count": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "level_of_study": {
                    "type": "string"
                },
                "major": {
                    "type": "string"
                },
                "phone_e164": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/store.ApplicationStatus"
                },
                "submitted_at": {
                    "type": "string"
                },
                "university": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "store.ApplicationListResult": {
            "type": "object",
            "properties": {
                "applications": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.ApplicationListItem"
                    }
                },
                "has_more": {
                    "type": "boolean"
                },
                "next_cursor": {
                    "type": "string"
                },
                "prev_cursor": {
                    "type": "string"
                }
            }
        },
        "store.ApplicationStats": {
            "type": "object",
            "properties": {
                "acceptance_rate": {
                    "type": "number"
                },
                "accepted": {
                    "type": "integer"
                },
                "draft": {
                    "type": "integer"
                },
                "rejected": {
                    "type": "integer"
                },
                "submitted": {
                    "type": "integer"
                },
                "total_applications": {
                    "type": "integer"
                },
                "waitlisted": {
                    "type": "integer"
                }
            }
        },
        "store.ApplicationStatus": {
            "type": "string",
            "enum": [
                "draft",
                "submitted",
                "accepted",
                "rejected",
                "waitlisted"
            ],
            "x-enum-varnames": [
                "StatusDraft",
                "StatusSubmitted",
                "StatusAccepted",
                "StatusRejected",
                "StatusWaitlisted"
            ]
        },
        "store.AuthMethod": {
            "type": "string",
            "enum": [
                "passwordless",
                "google"
            ],
            "x-enum-varnames": [
                "AuthMethodPasswordless",
                "AuthMethodGoogle"
            ]
        },
        "store.ShortAnswerQuestion": {
            "type": "object",
            "required": [
                "id",
                "question"
            ],
            "properties": {
                "display_order": {
                    "type": "integer",
                    "minimum": 0
                },
                "id": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "question": {
                    "type": "string",
                    "maxLength": 500,
                    "minLength": 1
                },
                "required": {
                    "type": "boolean"
                }
            }
        },
        "store.UserRole": {
            "type": "string",
            "enum": [
                "hacker",
                "admin",
                "super_admin"
            ],
            "x-enum-varnames": [
                "RoleHacker",
                "RoleAdmin",
                "RoleSuperAdmin"
            ]
        }
    },
    "securityDefinitions": {
        "CookieAuth": {
            "type": "apiKey",
            "name": "sAccessToken",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "HackPortal API",
	Description:      "API for HackPortal",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
